language: go
before_install:
  - go get github.com/ogier/pflag
  - go get github.com/mitchellh/gox
  - go get github.com/Sirupsen/logrus
  - go get github.com/mitchellh/go-homedir
  - gox -osarch="darwin/amd64 linux/amd64 windows/amd64"

script: make
deploy:
  provider: releases
  api_key: c18fccbfc0d53f7450c39912555ec4d74d3324a6
  file:
    - bin/windows/conoha-ojs.amd64.zip
    - bin/darwin/conoha-ojs-osx.amd64.gz
    - bin/linux/conoha-ojs-linux.amd64.gz

  skip_cleanup: true
  on:
    tags: true
    repo: naototty/conoha-ojs
    all_branches: true
